[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npm run build"
startCommand = "cd backend && mkdir -p data && npm start"
rootDir = "."

[variables]
NODE_ENV = "production"
PORT = "8080"
